name: Deploy for docker image

on:
  push:
    branches: ["master"]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: traefik-forward-auth
  IMAGE_NAME_FULL: ghcr.io/nbtca/traefik-forward-auth
  
jobs:
  Build-and-Push-to-DockerHub:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "master"

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          no-cache: true
          # target: deploy
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME_FULL }}
            ${{ env.IMAGE_NAME_FULL }}:latest